//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracking.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int IdProduct { get; set; }
        public string productName { get; set; }
        public int categoryId { get; set; }
        public int stockAmount { get; set; }
        public int price { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime deletedDate { get; set; }
    }
}
