//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracking.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int id { get; set; }
        public Nullable<int> product_Id { get; set; }
        public Nullable<int> customer_Id { get; set; }
        public Nullable<int> category_Id { get; set; }
        public Nullable<int> productSalesAmount { get; set; }
        public Nullable<int> productSalesPrice { get; set; }
        public Nullable<System.DateTime> salesDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
